name: 参加登録
description: Web Speed Hackathon 2022 の参加登録フォームです
title: '[参加登録]'
labels:
  - registration
body:
  - type: markdown
    attributes:
      value: |
        # ようこそ Web Speed Hackathon 2022 へ！

        **参加する前に、レギュレーションを確認してください**
  - type: dropdown
    id: regulation
    attributes:
      label: '注意事項・レギュレーション {{regulation}}'
      options:
        - 注意事項・レギュレーションを確認して、同意しました
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 計測対象の URL

        [課題のソースコード](https://github.com/CyberAgentHack/web-speed-hackathon-2022) から、アプリケーションをデプロイして、URL を提出してください
  - type: input
    id: target-url
    attributes:
      label: '計測対象の URL {{url}}'
      placeholder: e.g.) https://web-speed-hackathon-2022.example.com/
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## 準備が整いました

        投稿すると、GitHub Actions によって自動計測が始まります！

        - :information_source: もし、5分以上何も反応がない場合は、Slack で運営までご連絡ください
