pages:
  - name: ホーム - 未来
    path: /2022-08-07
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2022-08-01
  - name: 出走表
    path: /races/d0612e52-fc4e-47eb-9650-a1766e63c612/race-card
  - name: オッズ - 締め切り前
    path: /races/1e967dd7-273d-4ad4-8ca2-2400c77ebd75/odds
  - name: オッズ - 締め切り後
    path: /races/4f6bd70a-d342-45ec-9063-65271bf92972/odds
  - name: 結果
    path: /races/5fe32f6e-40b8-48ff-93ad-de540da18bd9/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
